services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - '8123:8123' # HTTP interface
      - '9000:9000' # Native interface
    environment:
      - CLICKHOUSE_DB=payloadtests
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse-users.xml:/etc/clickhouse-server/users.d/users.xml:ro
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:8123/ping']
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  clickhouse-data:
